/* Copyright 2025-2026 Eugene Petrenko (mcp@jonnyzzz.com); Copyright 2025-2026 JetBrains. Use of this source code is governed by the Apache 2.0 license. */
package com.jonnyzzz.mcpSteroid.gradle

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.WildcardTypeName
import com.squareup.kotlinpoet.asClassName
import com.squareup.kotlinpoet.buildCodeBlock
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File
import kotlin.math.absoluteValue
import kotlin.random.Random
import kotlin.reflect.KClass

abstract class CompilePromptsTask : DefaultTask() {
    @get:InputDirectory
    abstract val inputDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:OutputDirectory
    abstract val testOutputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val inputRoot = inputDir.get().asFile
        val outputRoot = outputDir.get().asFile
        val testOutputRoot = testOutputDir.get().asFile
        project.delete(outputRoot, testOutputRoot)
        project.mkdir(outputRoot)
        project.mkdir(testOutputRoot)

        val ctx = PromptGenerationContext(inputRoot, outputRoot, testOutputRoot)
        val generatedPrompts = mutableListOf<Pair<String, ClassName>>()

        inputRoot
            .walkTopDown()
            .filter { it.isFile }
            .forEach { src ->
                val relativePath = src.relativeTo(inputRoot).path
                val classType = ctx.geratePromptClazz(src)
                generatedPrompts.add(relativePath to classType)
            }

        generatePromptRegistry(ctx, generatedPrompts)
    }

    private fun generatePromptRegistry(ctx: PromptGenerationContext, prompts: List<Pair<String, ClassName>>) {
        val promptBaseClass = ClassName(ctx.packageName, "PromptBase")
        val kclassType = KClass::class.asClassName().parameterizedBy(
            WildcardTypeName.producerOf(promptBaseClass)
        )
        val mapType = Map::class.asClassName().parameterizedBy(String::class.asClassName(), kclassType)

        val mapEntries = CodeBlock.builder()
        prompts.forEachIndexed { index, (path, className) ->
            if (index > 0) mapEntries.add(",\n")
            mapEntries.add("%S to %T::class", path, className)
        }

        val registryProperty = PropertySpec.builder("registry", mapType)
            .addModifiers(KModifier.PRIVATE)
            .initializer(buildCodeBlock {
                add("mapOf(\n")
                indent()
                add(mapEntries.build())
                unindent()
                add("\n)")
            })
            .build()

        val getContentFun = FunSpec.builder("getContent")
            .addParameter("path", String::class)
            .returns(String::class.asClassName().copy(nullable = true))
            .addStatement("val promptClass = registry[path] ?: return null")
            .addStatement("val prompt = promptClass.java.getDeclaredConstructor().newInstance()")
            .addStatement("return prompt.readPrompt()")
            .build()

        val containsFun = FunSpec.builder("contains")
            .addParameter("path", String::class)
            .returns(Boolean::class)
            .addStatement("return path in registry")
            .build()

        val listPathsFun = FunSpec.builder("listPaths")
            .returns(Set::class.asClassName().parameterizedBy(String::class.asClassName()))
            .addStatement("return registry.keys")
            .build()

        val typeSpec = TypeSpec.objectBuilder("PromptRegistry")
            .addKdoc("Registry mapping resource paths to prompt classes.\nGenerated by compilePrompts task.")
            .addProperty(registryProperty)
            .addFunction(getContentFun)
            .addFunction(containsFun)
            .addFunction(listPathsFun)
            .build()

        val fileSpec = FileSpec.builder(ctx.packageName, "PromptRegistry")
            .addFileComment("GENERATED FILE - DO NOT EDIT")
            .addType(typeSpec)
            .build()

        ctx.outputRoot.resolve("PromptRegistry.kt").writeText(fileSpec.toString())
    }
}
