/* Copyright 2025-2026 Eugene Petrenko (mcp@jonnyzzz.com); Copyright 2025-2026 JetBrains. Use of this source code is governed by the Apache 2.0 license. */
package com.jonnyzzz.mcpSteroid.gradle

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import kotlin.math.absoluteValue
import kotlin.random.Random

abstract class GenerateMetadataTask : DefaultTask() {
    @get:Input
    abstract val versionString: Property<String>

    @get:Input
    abstract val timeBombDays: Property<Int>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val baseMagic = Random.nextInt().absoluteValue % 19456

        fun String.toEncodedSequence(): List<Int> {
            return reversed().map { it.code * baseMagic }
        }

        val versionCodes = versionString.get().toEncodedSequence()
        val timeBomb = LocalDateTime.now().plusDays(timeBombDays.get().toLong())
            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))
        val timeBombCodes = timeBomb.toEncodedSequence()

        val versionYields = versionCodes.joinToString("\n") { "yield($it)" }
        val timeBombYields = timeBombCodes.joinToString("\n") { "yield($it)" }

        val suppressAnnotation = AnnotationSpec.builder(Suppress::class)
            .addMember("%S, %S, %S", "MagicNumber", "unused", "NOTHING_TO_INLINE")
            .build()

        val getPluginVersionFun = FunSpec.builder("getPluginVersion")
            .addModifiers(KModifier.INLINE)
            .returns(String::class)
            .addKdoc("Plugin version (encoded)")
            .addCode("""
                |return sequence {
                |    $versionYields
                |}.map { it / $baseMagic }.toList().reversed().map { it.toChar() }.joinToString("")
            """.trimMargin())
            .build()

        val getTimeBombExpirationFun = FunSpec.builder("getTimeBombExpiration")
            .addModifiers(KModifier.INLINE)
            .returns(String::class)
            .addKdoc("Time bomb expiration date (encoded)")
            .addCode("""
                |return sequence {
                |    $timeBombYields
                |}.map { it / $baseMagic }.toList().reversed().map { it.toChar() }.joinToString("")
            """.trimMargin())
            .build()

        val isTimeBombExpiredFun = FunSpec.builder("isTimeBombExpired")
            .addModifiers(KModifier.INLINE)
            .returns(Boolean::class)
            .addKdoc("""
                |Check if time bomb has expired
                |@return true if the plugin is expired and should not function
            """.trimMargin())
            .addCode("""
                |val expiration = getTimeBombExpiration()
                |val now = java.time.LocalDate.now()
                |val expirationDate = java.time.LocalDate.parse(
                |    expiration,
                |    java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd")
                |)
                |return now.isAfter(expirationDate)
            """.trimMargin())
            .build()

        val validateTimeBombFun = FunSpec.builder("validateTimeBomb")
            .addModifiers(KModifier.INLINE)
            .addKdoc("""
                |Validate time bomb and throw exception if expired
                |@throws IllegalStateException if the plugin build has expired
            """.trimMargin())
            .addCode("""
                |if (isTimeBombExpired()) {
                |    throw IllegalStateException("This plugin build has expired, please update")
                |}
            """.trimMargin())
            .build()

        val fileSpec = FileSpec.builder("com.jonnyzzz.mcpSteroid", "PluginMetadata")
            .addFileComment("Auto-generated by Gradle - DO NOT EDIT")
            .addAnnotation(suppressAnnotation)
            .addFunction(getPluginVersionFun)
            .addFunction(getTimeBombExpirationFun)
            .addFunction(isTimeBombExpiredFun)
            .addFunction(validateTimeBombFun)
            .build()

        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(fileSpec.toString())
    }
}
