/* Copyright 2025-2026 Eugene Petrenko (mcp@jonnyzzz.com); Copyright 2025-2026 JetBrains. Use of this source code is governed by the Apache 2.0 license. */
package com.jonnyzzz.mcpSteroid.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import kotlin.math.absoluteValue
import kotlin.random.Random

abstract class GenerateMetadataTask : DefaultTask() {
    @get:Input
    abstract val versionString: Property<String>

    @get:Input
    abstract val timeBombDays: Property<Int>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val baseMagic = Random.nextInt().absoluteValue % 19456
        fun String.toEncodedSequence(): String {
            val codes = reversed().map { it.code * baseMagic }
            return codes.joinToString("\n        ") { "yield($it)" }
        }

        val versionEncoded = versionString.get().toEncodedSequence()
        val timeBomb = LocalDateTime.now().plusDays(timeBombDays.get().toLong())
            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))
        val timeBombEncoded = timeBomb.toEncodedSequence()

        val content = """
            |// Auto-generated by Gradle - DO NOT EDIT
            |@file:Suppress("MagicNumber", "unused", "NOTHING_TO_INLINE")
            |package com.jonnyzzz.mcpSteroid
            |
            |/**
            | * Plugin version (encoded)
            | */
            |inline fun getPluginVersion(): String {
            |    return sequence {
            |        $versionEncoded
            |    }.map { it / $baseMagic }.toList().reversed().map{ it.toChar() }.joinToString("")
            |}
            |
            |/**
            | * Time bomb expiration date (encoded)
            | */
            |inline fun getTimeBombExpiration(): String {
            |    return sequence {
            |        $timeBombEncoded
            |    }.map { it / $baseMagic }.toList().reversed().map{ it.toChar() }.joinToString("")
            |}
            |
            |/**
            | * Check if time bomb has expired
            | * @return true if the plugin is expired and should not function
            | */
            |inline fun isTimeBombExpired(): Boolean {
            |    val expiration = getTimeBombExpiration()
            |    val now = java.time.LocalDate.now()
            |    val expirationDate = java.time.LocalDate.parse(expiration,
            |        java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd"))
            |    return now.isAfter(expirationDate)
            |}
            |
            |/**
            | * Validate time bomb and throw exception if expired
            | * @throws IllegalStateException if the plugin build has expired
            | */
            |inline fun validateTimeBomb() {
            |    if (isTimeBombExpired()) {
            |        throw IllegalStateException("This plugin build has expired, please update")
            |    }
            |}
        """.trimMargin()

        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(content)
    }
}
